import sys
import os 
import json
from operator import itemgetter
from typing import List, Dict, Any, Optional

from langchain_core.messages import BaseMessage
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_community.vectorstores import FAISS

from multi_doc_chat.utils.model_loader import ModelLoader
from multi_doc_chat.exceptions.custom_exception import DocumentPortalException
from multi_doc_chat.logger import GLOBAL_LOGGER as log
from multi_doc_chat.prompts.prompt_library import PROMPT_REGISTRY
from multi_doc_chat.model.models import PromptType, ChatAnswer
from pydantic import ValidationError

class ConversationalRAG:
    """
    LCEL - based Conversational RAG with lazy retriever initialization.
    
    Usage:
        rag = ConverationalRag(session_id ="abc")
        rag.load_retriever_from_faiss(index_path="faiss_index/abc",k=5,index_name="index")  # Load retriever when needed
        answer = rag.invoke("What is ...?" , chat_history=[])
    """
    
    def __init__(self, session_id: Optional[str], retriever=None):
        try:
            self.session_id = session_id
            
            self.llm = self.__load_llm()
            self.contextual_prompt: ChatPromptTemplate = PROMPT_REGISTRY[
                PromptType.CONTEXTUALIZE_QUESTION.value
            ]
            
            self.qa_prompt: ChatPromptTemplate = PROMPT_REGISTRY[
                PromptType.CONTEXT_QA.value
            ]
            
            self.retriever = retriever
            self.chain = None
            if self.retriever is not None:
                self._build_lcel_chain()
        
            log.info("ConversationalRAg  initialized successfully.", session_id=self.session_id)
        except Exception as e:
            log.error(f"Error initializing ConversationalRAG: {str(e)}", session_id=self.session_id)
            raise DocumentPortalException(f"Initialization failed: {str(e)}") from e        
        
    def load_retriever_from_faiss(
        self,
        index_path: str,
        k: int = 5,
        index_name: str = "index",
        search_type: str = "mmr",
        fetch_k: int = 20,
        lambda_mult: float = 0.5,
        search_kwargs: Optional[Dict[str,Any]] = None
    ): 
        """
        Load FAISS vectorstores from disk and build retriever + LCEL chain.
        """
        
        try:
            if not os.path.isdir(index_path):
                raise FileNotFoundError(f"FAISS index directory not found: {index_path}")
            
            embeddings = ModelLoader().load_embedding_model()
            vectorstore = FAISS.load_local(
                index_path,
                embeddings,
                index_name,
                allow_dangerous_deserialization=True
            )
            
            if search_kwargs is None:
                search_kwargs = {"k": k}
                if search_type == "mmr":
                    search_kwargs["fetch_k"] = fetch_k
                    search_kwargs["lambda_mult"] = lambda_mult
                
            self.retriever = vectorstore.as_retriever(search_type=search_type, search_kwargs=search_kwargs)
            self._build_lcel_chain()
        
            log.info(f"FAISS retriever loaded successfully from {index_path}", session_id=self.session_id,search_type=search_type,fetch_k=fetch_k if search_type == "mmr" else None,lambda_mult=lambda_mult if search_type == "mmr" else None)
            return self.retriever
        except Exception as e:
            log.error(f"Error loading FAISS retriever: {str(e)}", session_id=self.session_id)
            raise DocumentPortalException(f"FAISS retriever loading failed: {str(e)}")
        
        
    def invoke(self, user_input: str, chat_history: Optional[List[BaseMessage]] = None) -> str:
        """ Invoke the LCEL pipeline. """
        try:
            if self.chain is None:
                raise DocumentPortalException("LCEL chain is not initialized. Please load a retriever first.",sys)
            chat_history = chat_history or []
            payload = {"input": user_input, "chat_history": chat_history}
            answer = self.chain.invoke(payload)
            if not answer:
                log.warning(
                    "No answer generated by LCEL chain.", user_input=user_input, session_id=self.session_id
                )
            
            try: 
                if isinstance(answer, str):
                    try:
                        answer_dict = json.loads(answer)
                    except json.JSONDecodeError:
                        answer_dict = {"answer": answer}
                else:
                    answer_dict = answer
                    
                validated = ChatAnswer.model_validate(answer_dict)
                answer = validated.answer

            except ValidationError as ve:
                log.error(f"Output validation failed: {str(ve)}", session_id=self.session_id)
                raise DocumentPortalException(f"Output validation failed: {str(ve)}") from ve
            
            log.info("LCEL chain invoked successfully.", user_input=user_input, session_id=self.session_id)
            return answer
        except Exception as e:
            log.error(f"Error invoking LCEL chain: {str(e)}", user_input=user_input, session_id=self.session_id)
            raise DocumentPortalException(f"LCEL invocation failed: {str(e)}") from e
            
             
        
    def __load_llm(self):
        try:
            llm = ModelLoader().load_llm()
            if not llm:
                raise ValueError("LLM loading failed: No model returned.")
            log.info("LLM loaded successfully.", session_id=self.session_id)
            return llm
        except Exception as e:
            log.error(f"Error loading LLM: {str(e)}", session_id=self.session_id)
            raise DocumentPortalException(f"LLM loading failed: {str(e)}") from e
        
    @staticmethod
    def _format_docs(docs)->str:
        return "\n\n".join(getattr(d,"page_content", str(d)) for d in docs)
    
    def _build_lcel_chain(self):
        try:
            if self.retriever is None:
                raise DocumentPortalException("Cannot build LCEL chain without a retriever.")
            
            question_rewriter = (
                {"input": itemgetter("input"), "chat_history": itemgetter("chat_history")}
                | self.contextual_prompt
                | self.llm
                | StrOutputParser()
            )
            
            retrieve_docs = question_rewriter | self.retriever | self._format_docs
            
            self.chain = (
                {
                    "context": retrieve_docs,
                    "input": itemgetter("input"),
                    "chat_history": itemgetter("chat_history")
                }
                | self.qa_prompt
                | self.llm
                | StrOutputParser()
            )
            
            log.info("LCEL chain built successfully.", session_id=self.session_id)
        except Exception as e:
            log.error(f"Error building LCEL chain: {str(e)}", session_id=self.session_id)
            raise DocumentPortalException(f"LCEL chain building failed: {str(e)}") from e
        
        
            